default_platform(:android)

platform :android do

    lane :build_android_debug do
        gradle(
          tasks: ["clean", "bundleDebug"]
        )
    end

    lane :build_android_release do
        gradle(
          tasks: ["clean", "bundleDebug"]
        )
    end

end