name: Release App


# When it will be triggered

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


#Where it will run

jobs:
  build:

    name: Build
    runs-on: macOS-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned."

#      - name: Restore learnAndroid.jks
#        run: |
#          echo "${{secrets.LEARNANDROID}}" > learnAndroid.jks.asc
#          gpg -d --passphrase learnandroid --batch learnAndroid.jks.asc > app/learnandroid.jks
      - run: echo "Setting up JDK"

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - run: echo "The workflow is now ready to test your code."

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.2.0
          bundler-cache: true

#      - name: Restore learnAndroid.jks
#        run: echo ${{secrets.KEYSTORE_LEARN_ANDROID}} | base64 -d > /home/runner/work/LearnAndroid/LearnAndroid/app/learnAndroid.jks
      - name: Restore learnAndroid.jks
        id: keystore_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'learnAndroid.jks'
          encodedString: ${{ secrets.KEYSTORE_LEARN_ANDROID }}


      - name: Restore fcm-android-key.json
        id: json_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'fcm-android-key.json'
          encodedString: ${{ secrets.GCP_KEY }}

      - run: echo "Upload apk to internal testing"

      - name: Build with Gradle
        run: bundle exec fastlane upload_build_internal
      - run: echo "Build status report=${{ job.status }}."